[webservers]
107.23.187.158 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/my-terraform-key.pem ansible_python_interpreter=/usr/bin/python3 ansible_ssh_extra_args='-q'
18.212.229.47  ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/my-terraform-key.pem ansible_python_interpreter=/usr/bin/python3 ansible_ssh_extra_args='-q'